name: ble
description: Sensor and data manager for Master's Thesis.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue: 0.6.3+1
  modal_progress_hud: ^0.1.3
  firebase_core: 0.4.4
  cloud_firestore: 0.13.4
  firebase_auth: 0.15.4
  cupertino_icons: ^0.1.2
  device_simulator: ^0.9.6
  wakelock: ^0.1.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/Inter-Regular-slnt=0.ttf
        - asset: assets/Inter-Bold-slnt=0.ttf
          weight: 800